
title: 'Illinois State Commission on Criminal Justice and Sentencing Reform'
company: 'Illinois State Commission on Criminal Justice and Sentencing Reform'
date: <%= new Date() %>
debug: TRUE

root: '/cjreform2015/'
domain: 'http://www.icjia.org'
#
# root: '/'
# domain: '127.0.0.1:9000'
