
title: 'Illinois State Commission on Criminal Justice and Sentencing Reform'
company: 'Illinois State Commission on Criminal Justice and Sentencing Reform'
dateCreated: <%= new Date() %>
debug: TRUE
keywords:
  - 'Illinois'
  - 'Criminal Justice'
  - 'Sentencing Reform'
  - 'Illinois Criminal Justice Information Authority'
  - 'Illinois State Commission on Criminal Justice and Sentencing Reform'
author: 'Illinois State Commission on Criminal Justice and Sentencing Reform'

description: "The website for the Illinois State Commission on Criminal Justice and Sentencing Reform"

#Social media
facebokContentType: 'article'
facebookAppId: '808662262561066'
facebookAuthorURL: 'https://www.facebook.com/ICJIA'

socialMediaImage: 'http://www.icjia.state.il.us/cjreform2015/img/icjia-default.jpg'

root: '/cjreform2015/'
domain: 'http://www.icjia.state.il.us'


# root: '/'
# domain: '127.0.0.1:9000'
