
title: 'Illinois Criminal Justice Comission'
base: ''
company: 'Illinois Criminal Justice Comission'
ga: 'UA-XXXXX-X'
date: <%= new Date() %>
debug: TRUE
breadCrumbs: TRUE
siteFolder: '/icjiadev/'
#siteFolder: '/cjillinois2015/'
